// Background particle art for FieldMotifs (the falling shapes on the red
// field) — data, not code, same spirit as contacts.json: add/remove/retune
// an asset here without touching the component.
//
// `recolor` picks which drawn tone in an asset gets swapped for
// `--main-light`. Unlike a CSS filter/blend trick (which can only ever
// approximate a swap, and only for pure black/white art), this is a real
// per-pixel replacement: each recolorable tone has a matching derived mask
// PNG at `public/particles/<basename>-mask-<tone>.png` (alpha = 1 exactly
// where that tone was drawn, 0 everywhere else, generated by color-distance
// thresholding against the source art — see the mask-generation recipe in
// CLAUDE.md's Asset workflows section). FieldMotifs paints a solid
// `--main-light` rect clipped to that mask directly on top of the base
// image, so the result is exact regardless of the tone's actual hex value —
// works the same for pure black/white line art (moon, candle, coffee,
// joker mask) and for the red-inked suit cards (hearts, diamonds), which a
// blend-mode duotone trick could never cleanly recolor (there's no black
// pixel in red ink for a multiply/screen swap to grab).
// 'none' skips the overlay entirely and renders the asset's own colors as-is.
// To change which tone reads as the accent color on a given asset, just
// flip its `recolor` value below — the matching mask file must already
// exist (regenerate via the CLAUDE.md recipe if you add a new asset).
export type MotifRecolor = 'white' | 'black' | 'red' | 'none';

export interface MotifAsset {
  src: string;
  recolor: MotifRecolor;
}

export const MOTIF_ASSETS: MotifAsset[] = [
  { src: '/particles/the moon.png', recolor: 'black' },
  // Too detailed to read at particle size while falling — commented out
  // rather than deleted, in case a bigger/slower-falling treatment later
  // makes them work.
  // { src: '/particles/tarot-candle.png', recolor: 'black' },
  // { src: '/particles/tarot-coffee.png', recolor: 'black' },
  { src: '/particles/joker-mask.png', recolor: 'white' },
  { src: '/particles/ace of spades-raster.png', recolor: 'black' },
  { src: '/particles/ace of hearts-raster.png', recolor: 'red' },
  { src: '/particles/ace of clovers-raster.png', recolor: 'black' },
  { src: '/particles/ace of diamonds.png', recolor: 'red' },
];

// Mask filenames follow `<src without extension>-mask-<tone>.png`.
export function motifMaskSrc(src: string, tone: Exclude<MotifRecolor, 'none'>): string {
  const lastDot = src.lastIndexOf('.');
  const base = lastDot === -1 ? src : src.slice(0, lastDot);
  return `${base}-mask-${tone}.png`;
}
